/*
 * AppProperties.java
 *
 * Created on 25 July 2008
 */

package funsoftware.properties;

/**
 * Manages global application properties
 * @author Matthew Sheets
 */
public class AppProperties {

    // Global constants
    /**
     * The application name
     */
    public static final String appName = "VisualNQC";
    
    /**
     * The application version
     */
    public static final String appVersion = "1.0";
    
    /**
     * The application name and version
     */
    public static final String appNameVersion = appName + " " + appVersion;
    
    /**
     * The name of the NQC code file generated by the application
     * NOTE: Filename must NOT contain spaces
     */
    public static final String appCodeFileName = "visual.nqc";

    
    public static String getProgramTypeID(){
        return appName + "-" + appVersion + ":" + getDeviceID();
    }
    
    // Application properties
    
    // The hardware device ID
    private static String _deviceID;
    public static String getDeviceID() {
        return _deviceID;
    }
    public static void setDeviceID(String deviceID) {
        _deviceID = deviceID;
    }
    
    // The hardware device name
    private static String _deviceName;
    public static String getDeviceName() {
        return _deviceName;
    }
    public static void setDeviceName(String deviceName) {
        _deviceName = deviceName;
    }
    
    // The IR tower communication tty type
    private static String _ttyType;
    public static String getTtyType() {
        return _ttyType;
    }
    public static void setTtyType(String ttyType) {
        _ttyType = ttyType;
    }
}
